# MCU name
MCU = RP2040
BOOTLOADER = rp2040

ALLOW_WARNINGS = yes
VIA_ENABLE = no
SHARED_EP_ENABLE = no
CONSOLE_ENABLE = yes
LTO_ENABLE = no
#OPT_DEFS = -O2 

SRC += woman.qgf.c
SRC += iosevka11.qff.c

QUANTUM_PAINTER_ENABLE  = yes
QUANTUM_PAINTER_DRIVERS = ssd1351_spi
DEBUG_MATRIX_SCAN_RATE_ENABLE = yes

LAYOUTS = ortho_1x1

# AUDIO 
AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware