# MCU name
MCU = RP2040
BOOTLOADER = rp2040

ALLOW_WARNINGS = yes
#PICO_INTRINSICS_ENABLED = no # ATM Unsupported by ChibiOS!
VIA_ENABLE = no
SHARED_EP_ENABLE = no
CONSOLE_ENABLE = no
LTO_ENABLE = no
OPT_DEFS = -O2


BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality


QUANTUM_PAINTER_ENABLE             = yes
QUANTUM_PAINTER_DRIVERS            += ssd1351_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes
QUANTUM_PAINTER_LVGL_USE_CUSTOM_CONF = yes

#DEBUG_MATRIX_SCAN_RATE_ENABLE = yes

LAYOUTS = ortho_1x1


# AUDIO 
AUDIO_ENABLE = no
AUDIO_DRIVER = pwm_hardware